### ISSUE TITLE
Dropbox: 5xx errors

### ISSUE THREAD

**Issue by IvanGoncharov** [darklynx/rest-api-collection#2]
Swagger doesn't support any patterns for error codes, see this:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#httpCodes
Instead you can use `default`:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-9
It's not ideal but it will pass validation.

**Comment by darklynx** [comment]
Is this only related to 5xx errors, or do you suggest to use `default` for any response except `200`? DropBox API uses HTTP error codes from 4xx and 5xx groups.

Actually here they have an example with `GeneralError` that uses schema: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responsesDefinitionsObject - this describes the global definitions for common responses, although I could not find an example how to refer them. Can that be something like this:

```
responses:
    200:
        description: ...
        schema: ...
    404:
        $ref: '#/responses/NotFound'
```

And here is an example with HTTP `405` error code: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operation-object-example

**Comment by IvanGoncharov** [comment]
`405` or any other particular number is valid but `5xx` as group is invalid.
Here is a [line](https://github.com/darklynx/swagger-api-collection/blob/master/api/yaml/dropbox-core.yaml#L157) where you use `5xx` as group of numbers.
And here is [line](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L334) in swagger schema that explicitly forbid such cases.

**Comment by darklynx** [comment]
Ah, sorry, I have misinterpreted your message, I though you are speaking about 5xx as a group of errors, whereas you pointed out that usage of any kind of string except `default` in response type is not allowed and that should always be a number. I'll just replace `5xx` with `500`.

What do you think about usage of global response definitions? Is it a good idea to use them, and is my example above correct?

**Comment by IvanGoncharov** [comment]
> What do you think about usage of global response definitions? Is it a good idea to use them, and is my example above correct?

If in API documentation all errors are placed in one table that clearly show that they have same meaning. Which is definitely a case for dropbox.
P.S. For me rule of thumb is, if two or more instances have same meaning replace them with ref to shared instance.
But I'm against wrapper types like:

``` yaml
MyInteger:
  type: integer
```

But if diffent story if you add some semantic meaning even if schema is exactly the same, like:

``` yaml
PrimeNumber:
  type: integer
```

**Comment by IvanGoncharov** [comment]
@darklynx Thanks.
