### ISSUE TITLE
Dropbox: body parameters in content API

### ISSUE THREAD

**Issue by IvanGoncharov** [darklynx/rest-api-collection#3]
`body` parameters should use `schema` instead of `type`:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#user-content-parameterSchema
Also it good idea to use special `file` type instead of `string` in this case you are using `consume` attribute.
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#user-content-data-types

**Comment by darklynx** [comment]
I'm not sure what is better to set:

```
schema:
        type: file
```

or to use something like:

```
  schema:
    $ref '#/definitions/FileContent'
...
definitions:
  FileContent:
      type: file
```

decided for the first approach, although JSON generator has generated 3 pseudo types

**Comment by IvanGoncharov** [comment]
@darklynx Thank you.
I think you made right decision, if you can't attach additional semantics it better to use inline schema.
Be cause in second approach you just showing that arguments has common type therefore share some semantic but don't provide anything except that all of them are files.
