### ISSUE TITLE
Instagram: duplicating schemas

### ISSUE THREAD

**Issue by IvanGoncharov** [darklynx/rest-api-collection#4]
https://github.com/darklynx/swagger-api-collection/blob/master/api/yaml/instagram.yaml#L1011
https://github.com/darklynx/swagger-api-collection/blob/master/api/yaml/instagram.yaml#L1270

**Comment by darklynx** [comment]
Thank you @IvanGoncharov !

I fixed the issue with duplicated entry and also done some renaming to reduce ambiguity in naming. Can you advice what tool did you use to validate the schema? I would like to discover such issues myself :)

**Comment by IvanGoncharov** [comment]
Funny enough, I simply update dependencies including `js-yaml`:
https://github.com/nodeca/js-yaml/issues/166

**Comment by darklynx** [comment]
@IvanGoncharov is that a tool you are using to convert YAML => JSON?

I'm using [swagger-codegen](https://github.com/swagger-api/swagger-codegen) with language `-l swagger` for output. It performs some validation of input file too, but funny enough ignores duplicated entries and simply replaces them, so the last wins, just like in the bug you mentioned above.

**Comment by IvanGoncharov** [comment]
> Is that a tool you are using to convert YAML => JSON?
> Yes. It also come with CLI tool:
> https://github.com/nodeca/js-yaml#usage
> So you can do conversion without writing JS code.

Best lib for validation if `sway`, it do a lot of additional checks:
https://github.com/apigee-127/sway/tree/master/docs#semantic-validation
And it's also used in `swagger-editor` so I try to improve it since improve quality of specs in the wild :)

I also work on template for API portal repo:
https://github.com/IvanGoncharov/SwaggerTemplateRepo/tree/master/spec
With entire API life cycle:
- Bundle spec from separate files
- Validate, serve over http, preview in SwaggerUI and ReDoc
- Travis integration to validate and deploy spec + ReDoc to gh-pages

I will ping you when it will be stable enough.
